# 数据的维度很重要

In [ ]:
# 一维：列表、集合
# 二维、三维（二维+时间）：多维列表
# 高维（键值对二元关系）：字典

# 数组（不同于列表，各个元素需要属性相同） N维对象 ndarray
# 列表：基于元素的计算思想；数组：基于数组整体的运算思想，不需要循环
# 组成：实际数据+描述数据的元数据（维度，数据类型）

In [3]:
import numpy as np

In [5]:
a = np.array([[0,1,2,3,4],[9,8,7,6,5]])

In [6]:
a


array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [7]:
print(a)


[[0 1 2 3 4]
 [9 8 7 6 5]]


In [8]:
a.ndim


2

In [9]:
a.shape


(2, 5)

In [10]:
a.size


10

In [11]:
a.dtype


dtype('int64')

In [12]:
a.itemsize


8

## 创建数组

In [16]:
# 从列表or元组创造
x = np.array([[1,2],(0.1,0.2)])
x

array([[1. , 2. ],
       [0.1, 0.2]])

In [21]:
np.arange(5)


array([0, 1, 2, 3, 4])

In [22]:
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.zeros((3,2),dtype=np.int32)


array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [35]:
np.full(shape=(2,3),fill_value=5)

array([[5, 5, 5],
       [5, 5, 5]])

In [29]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.ones_like(a)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.linspace(1,10,5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [44]:
a.reshape(5,2)


array([[0, 1],
       [2, 3],
       [4, 9],
       [8, 7],
       [6, 5]])

In [45]:
a.flatten()


array([0, 1, 2, 3, 4, 9, 8, 7, 6, 5])

In [47]:
a.astype(np.float64)


array([[0., 1., 2., 3., 4.],
       [9., 8., 7., 6., 5.]])

## 操作

In [51]:
#索引与切片
a

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [52]:
a[1]


array([9, 8, 7, 6, 5])

In [53]:
a[1][1:4:2]


array([8, 6])

In [55]:
a[:,1:4:2]


array([[1, 3],
       [8, 6]])

## 运算

### 数组与标量

In [57]:
b = np.arange(24).reshape((2,3,4))
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [59]:
b.mean()


11.5

In [61]:
b = b/b.mean()
b

array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
        [0.34782609, 0.43478261, 0.52173913, 0.60869565],
        [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],

       [[1.04347826, 1.13043478, 1.2173913 , 1.30434783],
        [1.39130435, 1.47826087, 1.56521739, 1.65217391],
        [1.73913043, 1.82608696, 1.91304348, 2.        ]]])

### 数组中元素运算

In [62]:
np.sqrt(a)
# abs fabs square log log10 log2 ceil floor
# rint modf cos sin tan exp sign

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [3.        , 2.82842712, 2.64575131, 2.44948974, 2.23606798]])

### 二元函数
对对应元素进行运算

In [ ]:
# + - * / ** > maximum minimum mod copysign
