# 数据的维度很重要

In [ ]:
# 一维：列表、集合
# 二维、三维（二维+时间）：多维列表
# 高维（键值对二元关系）：字典

# 数组（不同于列表，各个元素需要属性相同） N维对象 ndarray
# 列表：基于元素的计算思想；数组：基于数组整体的运算思想，不需要循环
# 组成：实际数据+描述数据的元数据（维度，数据类型）

In [3]:
import numpy as np

In [5]:
a = np.array([[0,1,2,3,4],[9,8,7,6,5]])

In [6]:
a


array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [7]:
print(a)


[[0 1 2 3 4]
 [9 8 7 6 5]]


In [8]:
a.ndim


2

In [9]:
a.shape


(2, 5)

In [10]:
a.size


10

In [11]:
a.dtype


dtype('int64')

In [12]:
a.itemsize


8

## 创建数组

In [16]:
# 从列表or元组创造
x = np.array([[1,2],(0.1,0.2)])
x

array([[1. , 2. ],
       [0.1, 0.2]])

In [21]:
np.arange(5)


array([0, 1, 2, 3, 4])

In [22]:
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros((3,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.full(shape=(2,3),5)


SyntaxError: positional argument follows keyword argument (2629436899.py, line 1)