### CSV的读写

In [1]:
import numpy as np


In [2]:
a = np.arange(100).reshape(5,20)


In [3]:
np.savetxt('/Users/murphy/Documents/GitHub/learn-py-basic-program/Data-Analyzes/Data/a.csv',a,fmt='%d',delimiter=',')


In [4]:
aa = np.loadtxt('/Users/murphy/Documents/GitHub/learn-py-basic-program/Data-Analyzes/Data/a.csv',delimiter=',')


### 多维数据的存取

In [5]:
b = np.arange(100).reshape(5,10,2)


In [7]:
b.tofile('/Users/murphy/Documents/GitHub/learn-py-basic-program/Data-Analyzes/Data/b.dat',format = '%d')


In [11]:
bb = np.fromfile('/Users/murphy/Documents/GitHub/learn-py-basic-program/Data-Analyzes/Data/b.dat',dtype=np.int64).reshape(5,10,2)


In [14]:
c = np.arange(100).reshape(5,10,2)

In [20]:
np.save('/Users/murphy/Documents/GitHub/learn-py-basic-program/Data-Analyzes/Data/c.npy',c)


In [21]:
cc = np.load('/Users/murphy/Documents/GitHub/learn-py-basic-program/Data-Analyzes/Data/c.npy')


In [22]:
cc

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

### 随机函数

In [26]:
np.random.rand()


0.378470363498689

In [27]:
np.random.randn()


-0.4108053671980164

In [32]:
np.random.randint(100,200)

199

In [33]:
np.random.randint(100,200,(2,3))


array([[102, 178, 129],
       [169, 108, 171]])

In [37]:
d = np.random.randint(100,200,(3,3))
d

array([[137, 118, 183],
       [154, 166, 138],
       [194, 175, 128]])

In [38]:
np.random.shuffle(d)
d

array([[154, 166, 138],
       [194, 175, 128],
       [137, 118, 183]])

In [41]:
dd = np.random.permutation(d)
d

array([[154, 166, 138],
       [194, 175, 128],
       [137, 118, 183]])

In [42]:
dd


array([[137, 118, 183],
       [194, 175, 128],
       [154, 166, 138]])

In [44]:
e = np.random.randint(100,200,8)
e

array([168, 102, 190, 174, 114, 129, 144, 112])

In [46]:
np.random.choice(e,(3,2))


array([[112, 114],
       [112, 144],
       [190, 168]])

In [47]:
np.random.choice(e,(3,2),replace=False)


array([[129, 112],
       [114, 174],
       [102, 190]])

In [49]:
np.random.choice(e,(3,2),p=e/np.sum(e))


array([[174, 190],
       [129, 102],
       [190, 114]])

In [50]:
np.random.uniform(1,10,(2,3))


array([[5.38832551, 2.34014177, 8.44342356],
       [7.56785583, 6.02865885, 7.66345347]])

In [52]:
np.random.normal(1,1,(2,3))


array([[ 1.02125951, -1.2871334 ,  1.07807834],
       [ 1.10451738,  1.19771305,  0.29282482]])

In [53]:
np.random.poisson(1,(2,3))


array([[1, 3, 0],
       [0, 2, 1]])

### 统计函数

In [55]:
# sum mean average std var (axis = 轴）
# min max argmin argmax unracel_index ptp median
f = np.arange(15).reshape(3,5)
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
np.sum(f)


105

In [57]:
np.sum(f,axis=0)


array([15, 18, 21, 24, 27])

In [58]:
np.sum(f,axis=1)


array([10, 35, 60])

In [59]:
np.average(f,axis=0,weights=[10,5,1])


array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

In [60]:
np.max(f)


14

In [62]:
np.argmax(f)


14

In [63]:
np.unravel_index(np.argmax(f),f.shape)


(2, 4)

In [64]:
np.ptp(f)


14

In [65]:
np.median(f)


7.0

### 梯度函数

In [67]:
# gradient
g = np.random.randint(0,20,(5))
g

array([19,  8, 14,  1, 18])

In [68]:
np.gradient(g)


array([-11. ,  -2.5,  -3.5,   2. ,  17. ])

In [70]:
gg = np.random.randint(0,20,(3,5))
gg

array([[ 9, 16,  4,  6, 11],
       [14,  5,  5,  2,  5],
       [14,  0, 14,  1,  7]])

In [71]:
np.gradient(gg)


[array([[  5. , -11. ,   1. ,  -4. ,  -6. ],
        [  2.5,  -8. ,   5. ,  -2.5,  -2. ],
        [  0. ,  -5. ,   9. ,  -1. ,   2. ]]),
 array([[  7. ,  -2.5,  -5. ,   3.5,   5. ],
        [ -9. ,  -4.5,  -1.5,   0. ,   3. ],
        [-14. ,   0. ,   0.5,  -3.5,   6. ]])]